name: friday
description: Your Personal Class Manager Assistant, It'll never let you miss another assignment deadline or upcoming test.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.0
  cupertino_icons: ^1.0.5
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  email_validator: ^2.0.1
  google_sign_in: ^5.3.3
  uuid: ^3.0.6
  url_launcher: ^6.1.3
  firebase_storage: ^10.2.18
  path_provider: ^2.0.11
  date_time_picker: ^2.1.0
  table_calendar: ^3.0.6
  flutter_login_facebook: ^1.5.0+1
  flutter_icons_null_safety: ^1.1.0
  firebase_core: ^1.18.0
  image_picker: ^0.8.5+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
